import type { Metadata } from "next";
import localFont from "next/font/local";
import { config } from '@fortawesome/fontawesome-svg-core'
import '@fortawesome/fontawesome-svg-core/styles.css'
config.autoAddCss = false
import '@/app/styles/layout.css'

import { ThemeProvider } from '@/app/config/theme/ThemeProvider'

import GeneralMenu from '@/app/components/GeneralMenu'

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {

  return (
    <html lang="en">
      <body>
        <ThemeProvider>
          <GeneralMenu />
          {children}
        </ThemeProvider>

      </body>
    </html>
  );
}
