import type { Metadata } from "next";
import localFont from "next/font/local";
import "@/app/globals.css";
import CookieConsent from "@/components/CookieConsent";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function LoginLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {


  return (
    <html lang="en">
      <body className="relative">
      {children}
      </body>
    </html>
  );
}
